name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: golang:1.22-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format check
        run: |
          diff=$(gofmt -l -s .)
          if [ -n "$diff" ]; then
            echo "Go files are not formatted correctly:"
            echo "$diff"
            exit 1
          else
            echo "Go files are formatted correctly."
          fi

      - name: Run tests
        run: go test ./...
